modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="balancedflight"
version="${file.jarVersion}"
displayName="Balanced Flight"
logoFile="examplemod.png"
credits="TeamDeusVult for original idea, code, and assets."
authors="CorgiBlu"
description="This mod adds an Angel Ring, which allows you to fly, like in a creative mode."
[[dependencies.balancedflight]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.balancedflight]]
    modId="minecraft"
    mandatory=true
versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.balancedflight]]
    modId="curios"
    mandatory=true
    versionRange="[1.18.2-5.0.7.1,)"
    side="BOTH"
